language: go

env:
  - GO111MODULE=off

go:
  - 1.13.x
  - 1.14.x
  - 1.15.x
  - master

matrix:
 fast_finish: true
 allow_failures:
   - go: master

sudo: false

script: 
 - go test -v -cpu=2
 - go test -v -cpu=2 -race
 - go test -v -cpu=2 -tags noasm
 - go test -v -cpu=2 -race -tags noasm
